# Generated by Django 4.1.7 on 2023-03-31 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MagV1', models.IntegerField()),
                ('MagV2', models.IntegerField()),
                ('MagV3', models.IntegerField()),
                ('engine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine_readings.engine')),
            ],
        ),
    ]
