# Generated by Django 4.1.7 on 2023-03-27 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine_readings', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Readings',
            new_name='Reading',
        ),
    ]
